name: Bug Report
description: Report something that's broken
title: "[fix] "
labels: ["type:fix"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Environment
      description: |
        - Atlas version:
        - Python version:
        - OS:
        - Agent (Claude Desktop, Zed, etc.):
        - Installed modules:
    validations:
      required: false
