name: New Module
description: Request or contribute a new module bundle
title: "[module] "
labels: ["type:feat", "comp:modules"]
body:
  - type: input
    id: module_name
    attributes:
      label: Module name
      placeholder: e.g., "svelte", "deno", "bun"
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - language
        - linter
        - formatter
        - testing
        - framework
        - database
        - vcs
        - platform
        - pkg_manager
        - environment
        - ci_cd
        - stack
        - tool
        - prompt
    validations:
      required: true
  - type: textarea
    id: detect_files
    attributes:
      label: Detection files
      description: Which files signal this tool is present? (e.g., "pyproject.toml, .ruff.toml")
    validations:
      required: false
  - type: textarea
    id: rules
    attributes:
      label: Draft rules.md content
      description: What rules should this module teach agents?
    validations:
      required: false
